# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal <- function(mu, sigma) {
    .Call(`_simSavings_normal`, mu, sigma)
}

cppi_c <- function(nsim, alpha, sigma, a, years, pi) {
    .Call(`_simSavings_cppi_c`, nsim, alpha, sigma, a, years, pi)
}

alt_c <- function(alpha, sigma, a, years, nsim, K, A_factor) {
    .Call(`_simSavings_alt_c`, alpha, sigma, a, years, nsim, K, A_factor)
}

alt_mort_c <- function(alpha, sigma, a, years, nsim, K, A_factor, M) {
    .Call(`_simSavings_alt_mort_c`, alpha, sigma, a, years, nsim, K, A_factor, M)
}

cppi_mort_c <- function(nsim, alpha, sigma, a, years, pi, M) {
    .Call(`_simSavings_cppi_mort_c`, nsim, alpha, sigma, a, years, pi, M)
}

sort_c <- function(vec) {
    .Call(`_simSavings_sort_c`, vec)
}

length_c <- function(vec) {
    .Call(`_simSavings_length_c`, vec)
}

median_c <- function(vec) {
    .Call(`_simSavings_median_c`, vec)
}

equiv_pi_c <- function(m, ret, nsim, alpha, sigma, a, years, pi) {
    .Call(`_simSavings_equiv_pi_c`, m, ret, nsim, alpha, sigma, a, years, pi)
}

return_c <- function(vec, a, years) {
    .Call(`_simSavings_return_c`, vec, a, years)
}

rcpp_hello_world <- function() {
    .Call(`_simSavings_rcpp_hello_world`)
}

